### ISSUE TITLE
Migrate wapiti.sourceforge.io to wapiti.github.io

### ISSUE THREAD

**Issue by fwininger** [wapiti-scanner/wapiti#10]
Use Github pages to migrate wapiti.sourceforge.io

**Comment by devl00p** [comment]
Website copied to https://wapiti-scanner.github.io/
Github didn't allow to have wapiti.github.io as the org name is wapiti-scanner.

I changed links in the webpage to Github ones, expect for downloading as no tarball / zip release is available on Github yet.

**Comment by devl00p** [comment]
related repository : https://github.com/wapiti-scanner/wapiti-scanner.github.io
