### ISSUE TITLE
Authentication and cookies

### ISSUE THREAD

**Issue by superseby2** [wapiti-scanner/wapiti#103]
Hello, 

Thanks for Wapiti. I am starting to using it and had a strange result I would need to understand., because I fear Wapiti managed to find a way to Post things on behalf of another user. 

Our site is using Session Cookies and remember cookies : when the session expires the user gets "reconnected" if the remember cookie is  alive and well. 

- I ran a first scan using -c chrome thinking it would pick up all the cookies from chrome.  (but did not check with session was "live")

That's when I realize many "Hi there!" posts (our app has a blog-like post system) in several places from a user I am not sure I was not connected to in Chrome. 

- I stopped the scan (right after it starts [*] Launching module exec)
- Started chrome and realize I was not automatically connected.  ... (so no valid remember cookie)

Si I am not sure *how* the scan managed to make those post : 

- Did it manage to have the right cookies at that time and when I launched Chrome, bad luck, they were expired ?
- Stopping the scan, does some "cookie cleaning" somehow ? (unlikely)

I tried to generate a report, but it takes for ages and nothing comes out. 

I tried to re-run the scan with --flush-session but never managed to reproduce those posts.  
One last thing : during the Scan that managed to do those posts, the number of url found was x2 those found during the following scans. 

It would be so nice if you could shed some light on this, or more at least what -c chrome does . 

Thx!

**Comment by superseby2** [comment]
Update : I managed to reproduce one "Hi there!" post using -a and --auth-type post and using the credential of the same user .. but I had only one post and not all the others from other part of the site  : it seems like urls discovery is not consistent between runs ?

**Comment by superseby2** [comment]
Last question : I kept the Scan files (db, and the other one). Is there a way for me to find in the db if a the session has been used ? 
Thx again.

**Comment by devl00p** [comment]
Hello,

I guess you are using the code from the repository as `-c chrome` is not part of last stable release (3.0.4).

This option will create a cookie jar with all cookies from the browser and then the `requests` library we are using for HTTP requests will use those cookies when they match the scanned domain.

Note that due to a bug in the module importing cookies we have to remove the expiration date on cookies before using them. It has no effect on the cookies inside your browser though.

Of course there are no intentional cookie cleaning but indeed the crawl order may vary and if the crawler see some logout URL it can have an effect on those cookies.

If your website is not using TLS you can use wireshark to record the network traffic otherwise the best option would be to set up OWASP ZAP (or Burp) as an intercepting proxy to see what is hapenning.

https://medium.com/@hiregovindawagle/owasp-zap-how-to-intercept-https-sites-f41b2247785c

**Comment by superseby2** [comment]
Thanx very much for the quick response.

I am looking at the SQLlite db for this scan and I see some /logout so it most definitively had an impact on what I saw when opening manually my browser :)

I am still digging but it looks like POST were "legit" after all.

Thx for the suggestions. I am discovered ZAP and it is quite impressive as Wapiti. 

As for the version I used pip to install wapiti3 not got it from git. With this version, I did not manage to get a report . (it might take more time than I was prepared to wait?)

Thx again !

**Comment by superseby2** [comment]
Sorry to bother, but I would have one last question : in the SqlLite DB, I clearly see a call to logout URL but following calls are still handled as if the user was still connected. I am assuming the URL in the table *paths* are in the order of the test?  each request happening one after the other?

**Comment by superseby2** [comment]
I found at that our remember cookie seems to be still valid after a logout :scream: . 
Thx for  allowing us to uncover this!

**Comment by bretfourbe** [comment]
Hi @superseby2,
Good to know that you found an interesting issue thanks to wapiti :)
For your tests, you can also try to exlude the logout URL with `-x / --exclude` option, this will prevent wapiti from being disconnected during the scan.

**Comment by superseby2** [comment]
Yes thx! I did another test with -x to exlude the logout part. and the report (took a while) but got generated fine.

One suggestion : I might have missed it, but I could not see any mention regarding the fact that real POST with real test content about ... everywhere. For systems like CMS or Blogs, one could end-up with a website with a configuration pretty much messed-up. So something like  /!\ do not use on a production system /!\ might come handy. I think.

**Comment by devl00p** [comment]
Indeed, I will create an issue about this.

Regards
