### ISSUE TITLE
setup.py includes tests as a package

### ISSUE THREAD

**Issue by wykwit** [wapiti-scanner/wapiti#107]
Currently `setup.py` uses simple `find_packages()` call which includes 'tests', 'tests.attack', 'tests.cli', 'tests.endpoint', 'tests.parsers', 'tests.payload' and 'tests.web' in a list of packages.
This results in `tests` being installed under site-packages in a separate 'tests' folder next to wapitiCore.

```
$ ls lib/python3.9/site-packages 
tests  wapiti3-3.0.4-py3.9.egg-info  wapitiCore
```

The solution would be to use `find_packages()` with additional exclude parameter, like so:
```
find_packages(exclude=['tests', 'tests.*'])
```

**Comment by devl00p** [comment]
Thank you for reporting this
