### ISSUE TITLE
Test HTTP to HTTPS redirection

### ISSUE THREAD

**Issue by fwininger** [wapiti-scanner/wapiti#118]
add test to validate the presence of the redirection from http to https.

**Comment by tarraschk** [comment]
Up.

**Comment by tarraschk** [comment]
@OussamaBeng si tu peux regarder ça cette semaine

**Comment by bretfourbe** [comment]
This is fixed by `https_redirect` module : https://github.com/wapiti-scanner/wapiti/pull/411
