### ISSUE TITLE
Module SSRF is broken

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#121]
The module SSRF is not working anymore with wapiti3.ovh.

It looks like wapiti3.ovh does not support the new naming convention from https://github.com/wapiti-scanner/wapiti/commit/2427197966f27b7de12d285ac6e4280a1d7f2645

**Comment by devl00p** [comment]
Indeed I need to make a retro-compatible php code on wapiti3.ovh. It will be done before a new stable release is made.

**Comment by devl00p** [comment]
Fixed

```
---
Vulnérabilité SSRF dans http://testphp.vulnweb.com/showimage.php via une injection dans le paramètre file
Evil request:
    GET /showimage.php?file=http%3A%2F%2Fexternal.url%2Fpage HTTP/1.1
    Host: testphp.vulnweb.com
---
```
