### ISSUE TITLE
Test on xxe module fail in github actions

### ISSUE THREAD

**Issue by bretfourbe** [wapiti-scanner/wapiti#125]
Hi Nicolas,
I have an issue with my MR https://github.com/wapiti-scanner/wapiti/pull/124 that i can't reproduce on my side.
![image](https://user-images.githubusercontent.com/27951656/122049103-522e4880-cde2-11eb-866e-6ced9139f38a.png)
Do you have any idea ?
Thanks in advance

**Comment by devl00p** [comment]
Hello

I wans't able to reproduce but you ca use asyncio debug mode to get more information: https://docs.python.org/3/library/asyncio-dev.html#debug-mode

You can also fix httpx and respx to specific versions. I know that httpx 0.18.1 along with respx 0.17.0 work well.

**Comment by devl00p** [comment]
My bad, this is not related to asyncio :p I guess this is related to the version of PHP used or one of its modules

**Comment by devl00p** [comment]
The output shows PHP 8.0.7 while it should be running PHP 7 :thinking:

**Comment by devl00p** [comment]
Indeed

![capt](https://user-images.githubusercontent.com/20163212/122126623-508c7100-ce32-11eb-9bd0-b1114da21a37.png)

**Comment by devl00p** [comment]
Explicitly calling the `php7.4` binary in `test_mod_xxe.py` fixes the issue. I applied the change on master
