### ISSUE TITLE
Trying to run wapiti on BWAPP but i think the cookie doesn't work

### ISSUE THREAD

**Issue by traubas** [wapiti-scanner/wapiti#129]
first i ran the wapiti-getcookie script on the login page: http://<ip>:8001/login.php to get the session cookie.
then i ran wapiti on the http://<ip>:8001/sqli_1.php
but i get no results... only results about flags missing or headers...
has anyone else been able scan bwapp?

**Comment by bretfourbe** [comment]
Hi @traubas,
Please, can you give the command you are using for your scan ?
Thanks in advance

**Comment by devl00p** [comment]
Indeed the login form is using a `button` field with a value. We are supporting `input type=button` but not that kind of field.

**Comment by devl00p** [comment]
fixed in latest commot
