### ISSUE TITLE
False positives in modules nikto and buster

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#139]
Some servers are configured to reply with a 200 response even if a file is missing.

Such false positives should be checked and fixed in both modules. For example by trying to query an unlikely existing document and comparing the response.

Example of line in nikto_db that may cause such behavior:

`001924,3092,1,/weblog/,GET,200,,,,,This might be interesting.,,`

**Comment by tarraschk** [comment]
Seems close to #160 

Another approach might be looking at the type of file that we get: if we get an HTML page for a file request, that's certainly a "Page not found", whereas if we get binary data, that's certainly a real backup file
