### ISSUE TITLE
Is there a passive mode?

### ISSUE THREAD

**Issue by peter17** [wapiti-scanner/wapiti#157]
Hi,

I have a question that could be in the FAQ or in the main README: is there a "passive" / "non-intrusive" mode that would perform only checks that would not harm the target?

For instance: search for potentially dangerous files on the server, folder and file enumeration, checking HTTP security headers, etc.

Thanks in advance

**Comment by bretfourbe** [comment]
Hi @peter17,

For now, there is no such "passive" mode. You need to use `-m` option with the modules that you want to use to do something similar.

@devl00p do you think we could define a "passive" mode like it is done for "common" for instance ?

**Comment by devl00p** [comment]
Yes indeed, a new group could be added for modules that doesn't use attack payloads.

**Comment by devl00p** [comment]
`-m passive` is available in latest stable release
