### ISSUE TITLE
Faux positif lors de codes de retour 303 sur les injections SQL

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#158]
Lors de tentatives d'injections SQL, un code de retour 303 est pris comme une injection SQL réussie.

Cela provoque des faux positifs, notamment sur les outils Moodle, où le formulaire d'authentification répond 303 à des requêtes d'injections.

**Comment by devl00p** [comment]
Aurais tu le path d'une de ces URLs moodle problématique ? ou une adresse partagable pour reproduire ce comportement ?

**Comment by devl00p** [comment]
Je pense que j'ai trouvé (si c'est dans la page de login de moodle)

**Comment by devl00p** [comment]
J'ai pu investiguer et malheureusement c'est spécifique au comportement de Moodle et de la façon dont il redirige les utilisateurs sur le formulaire de login.

En gros à la soumission du formulaire on obtient un 303 avec redirection sur la même URL. Wapiti gère la redirection lui-même, en l’occurrence il ne l'a suit pas ici mais lors de l'envoi du payload suivant Moodle considère qu'il a affaire au visiteur qui a rechargé la page et lui livre un HTTP 200.

Pour faire court une requête sur deux on a un 303 et alternativement un 200.

Exemple:

```python
import requests

sess = requests.session()

for __ in range(5):
    resp = sess.post(
            "https://moodle.univ-lille.fr/login/index.php?authCAS=NOCAS",
            data={
                "anchor": "",
                "logintoken": "alice",
                "username": "alice",
                "password": "",
                "rememberusername": 1
            },
            allow_redirects=False
    )
    print(resp.status_code)
```

Output généré:
```
303
200
303
200
303
```

La logique de test de Wapiti est bonne mais comme les payloads envoyés ont des tests qui alternent (Faux - Vrai - Faux - Vrai) on arrive à ce type de situation.

Forcer à suivre les redirections pour le module sql fixe le problème sur Moodle mais risque de générer des faux négatifs potentiels, le plus propre est d'avoir une suite de test Faux - Faux - Vrai - Vrai (ou Vrai - Vrai - Faux - Faux)

**Comment by tarraschk** [comment]
Je confirme, c'était du Moodle et sur la page de login :)
