### ISSUE TITLE
Faux positif lors de codes 303 sur les Backups

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#160]
Lors de recherches de fichiers de backup oubliés, un code de retour 303 ou 200 est pris comme un fichier de backup potentiel.

Cela provoque des faux positifs, notamment sur les sites où les erreurs 404 sont mal implémentées et où toute requête provoque soit une redirection soit un code 200 direct.

L'idéal serait certainement de regarder si la page obtenue est en fait du HTML ou du vrai binaire ?

**Comment by fwininger** [comment]
Je pense que regarder si la page n'est pas du html c'est bien. Les entêtes des fichiers peuvent etre très différentes selon les "backup".

**Comment by devl00p** [comment]
Malheureusement s'il s'agit d'un backup de page web (html, php) et si le serveur fait un équivalent du mime sniffing on peut s'attendre à avoir un content-type html et donc un faux négatif.

Je propose à la place qu'on fasse un test supplémentaire pour voir ce que donne une requête supplémentaire pour un fichier improbable dans le dossier testé.

Ça semble en tout cas fonctionner pour http://testphp.vulnweb.com/Mod_Rewrite_Shop/
