### ISSUE TITLE
module permanentxss causes error

### ISSUE THREAD

**Issue by Sascha-Block** [wapiti-scanner/wapiti#175]
Running Wapiti-3.0.1 causes error in run of `wapiti -u https://domain.com/`

...
[*] Launching module permanentxss
Traceback (most recent call last):
  File "/usr/bin/wapiti", line 11, in <module>
    load_entry_point('wapiti3==3.0.1', 'console_scripts', 'wapiti')()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 1002, in wapiti_main
    wap.attack()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 445, in attack
    self.report_gen.generate_report(self.output_file)
  File "/usr/lib/python3/dist-packages/wapitiCore/report/htmlreportgenerator.py", line 57, in generate_report
    copytree(os.path.join(self.BASE_DIR, self.REPORT_DIR, subdir), os.path.join(output_path, subdir))
  File "/usr/lib/python3.7/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3/dist-packages/wapitiCore/report_template/js'

**Comment by Sascha-Block** [comment]
@bretfourbe **wapiti is already the latest version (3.0.1+dfsg-1).**

I've seen that 3.0.5 is available, but not for my installation method.
Please note that "You may find some useful informations in the README" (which is mentioned in https://wapiti.sourceforge.io/) with that link to **https://github.com/wapiti-scanner/wapiti/blob/master/README.md** does not seem up to date either, due it leads to an 404 page 

pi@raspberrypi:/bin $ sudo apt-get install wapiti
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
wapiti ist schon die neueste Version (3.0.1+dfsg-1).
Die folgenden Pakete wurden automatisch installiert und werden nicht mehr benötigt:
  gconf-service gconf2-common libexiv2-14 libgconf-2-4 libgfortran3
  libgmime-2.6-0 libllvm8 libmicrodns0 libncurses5 libssl1.0.2 libva-wayland2
  python-colorzero rpi-eeprom-images uuid-dev
Verwenden Sie »sudo apt autoremove«, um sie zu entfernen.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 2 nicht aktualisiert.

**Comment by devl00p** [comment]
Closing this issue as it was more related to an invalid packaging. User feedback during scan is another problem and won't be easy to solve (several attempts have already been made) but at least since wapiti 3.0.7 the crawler and some attack modules are faster due to requests being sent concurrently.
