### ISSUE TITLE
Raise an error if --auth-cred is used without --auth-type

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#181]
Currently `-a` (long option is `--auth-cred`) can be used without specifying `--auth-type` as `self._auth_method` is initialized to  "basic" in `crawler.py` ( https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/net/crawler.py#L176 )

BUT the fact that auth basic is used as default auth method is not mentionned either in `wapiti -h` or Wapiti manpage.

Users MAY expect that the default auth method is "post", not "basic"  but instead of changing the default auth method I think it would be better to force the user to specify `--auth-cred` when `-a` is set making it more clear to anyone.

**Comment by tres1N** [comment]
So if `-a` is set, `--auth-type` will have to be specified as well.

And which error should be raised otherwise? 
just InvalidOptionValue?
