### ISSUE TITLE
TLS/SSL Certificate rating module

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#182]
This issue serves as a suggestion to add a new module to rate (from A to F)  the certificate of a web server and requires more research on the topic.

The methodology can be taken from https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide

SSL Labs provides a list of existing assessment tools here: https://github.com/ssllabs/research/wiki/Assessment-Tools#server-assessment

One of those is https://github.com/nabla-c0d3/sslyze which is using Python.

I don't know to which extent we can reuse an existing python tool or library to implement the whole methodology and if all attack checks can be done using only an up-to-date TLS library (like openssl, which may have removed deprecated cryptograms from its code base though).

**Comment by fwininger** [comment]
There are several issues dealing with this issue.

The most important issue is with the version of the https client used by python.

We had done test with an openssl backend or any modern client, you cannot establish a connection in SSLv3 / SSLv2, or any very bad ciphers. Thus the module will miss the most important vulnerabilities :(
To address this problem we are using nmap with the ssl-enum-ciphers script. Nmap  has its own client 

Another advantage is that we are not limited to do TLS on the HTTPS port and we do it on all TLS ports.

**Comment by devl00p** [comment]
I played with sslyze and it seems able to provide almost everything that ssllabs provide.

However calculating a unique rating seems hard and would require lot of maintenance.

I saw that even ssllabs is not clear about how they are rating TLS 1.3, it is not even mentionned in their rating guide and they have several opened issues for this cypher on their bugtracker.

I guess it would be better to simply warn for each particular issues (like use of outdated cypher suites, bad algorithms like RC4, specific flaws like heartbleed/robot and certificate validity).

Last time I checked sslyze was using an old version of cryptography for the stable release because the cryptography module changed their versionning which is now fixed on sslyze git repository meaning we would be able to use sslyze without having to downgrade cryptography.

About performance I found sslyze to be a bit slow even if the code is using threads but I haven't taken a deeper look at its internals.

**Comment by devl00p** [comment]
I get different ratings for some ciphers.

For example TLS_RSA_WITH_SEED_CBC_SHA is considered weak by ssllabs and cyphersuite ( https://ciphersuite.info/cs/TLS_RSA_WITH_SEED_CBC_SHA/ ) but Nmap is considering it as a "A"

Also Immuniweb marks it as "Good configuration" in their  PCI DSS test but  "Non-compliant with NIST guidelines" in another test :sweat_smile:
