### ISSUE TITLE
Detect WordPress version

### ISSUE THREAD

**Issue by polyedre** [wapiti-scanner/wapiti#187]
The tool `wpscan` uses the feeds to identify the version of WordPress.

Two feeds are available at `/feed/` and `/comments/feed/` (the latter is available even if comments are disabled). These feeds contain the `generator` tag which leaks the version:

```xml
<channel>
	<title>REDACTED</title>
	<atom:link href="https://REDACTED/feed/" rel="self" type="application/rss+xml" />
	<link>https://REDACTED</link>
	<description>REDACTED</description>
	<generator>https://wordpress.org/?v=5.8.1</generator>
```

I think we could add a module that specializes in identifying the version of WordPress as this is a popular CMS.

**Comment by bretfourbe** [comment]
Maybe in `mod_wp_enum`attack module ?

**Comment by devl00p** [comment]
What about adding special case in our wappalyzer module ?

**Comment by devl00p** [comment]
@polyedre @fwininger I think we can close this issue now ?

I know that wpscan is also able to detect the Wordpress version using some files from the plugins but it may be the subject of another issue later.
