### ISSUE TITLE
ERROR: httpx 0.20.0 has requirement httpcore<0.14.0,>=0.13.3, but you'll have httpcore 0.14.1 which is incompatible.

### ISSUE THREAD

**Issue by ricohomewood** [wapiti-scanner/wapiti#189]
When using pip to install wapiti, I get this error when trying to install.

I can see that the `httpcore` library was updated to `0.14.1` recently and as such the `httpx` library was updated to `0.21.0` to address this.

Please can you update the version pin of `httpx` that wapiti uses, so we can get past the installation error, or pin the version of `httpcore` to at least `0.14.0`?

I see these errors in the install log:

```
ERROR: httpx 0.20.0 has requirement httpcore<0.14.0,>=0.13.3, but you'll have httpcore 0.14.1 which is incompatible.
```
This may be because we allow the following ` httpcore>=0.13.7` so will always pick latest:

```
Collecting httpcore>=0.13.7
  Downloading httpcore-0.14.1-py3-none-any.whl (55 kB)
```

httpx release: https://github.com/encode/httpx/releases/tag/0.21.0

**Comment by devl00p** [comment]
Indeed I saw the httpx release too. I will make a PR to fix this soon

**Comment by devl00p** [comment]
httpx-socks currently has conflicts with this version, need more time

**Comment by ricohomewood** [comment]
Thanks for fixing so quickly. Will this release make its way to the Python Pip package manager as that still shows 3.0.7 only? Thanks

**Comment by devl00p** [comment]
Yes, I'm currently away for my computer but a release should appear soon (hopefully tonight)

Regards

**Comment by devl00p** [comment]
Just did it in fact :)
