### ISSUE TITLE
Detect Microsoft Exchange version

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#196]
When exploring Microsoft Exchange interfaces exposed on the Internet, our web application scanning engine does not find the Exchange version.

We already do that with our authenticated agent-based or agentless scans with Cyberwatch, but that would be really great to enhance Wapiti in order to be able to identify Exchange versions with just a web scan as well.

Moreover, Exchange exposes its version in its headers.

A request on the /owa/ URI will provide a X-OWA-Version header in its response, with appropriate information.

/!\ IMPORTANT /!\ : the X-OWA-Version header can be lowercased, so the parser MUST be case-insensitive.

Some examples below already indexed on Shodan:

```
 curl -v https://216.176.178.100/owa/ -k --silent 2>&1 | grep -i "X-OWA-Version"
< X-OWA-Version: 15.0.1497.26
```

```
curl -v https://185.17.193.231/owa/ -k --silent 2>&1 | grep -i "X-OWA-Version"
< x-owa-version: 15.1.2242.12
```

```
curl -v https://216.176.178.100/owa/ -k --silent 2>&1 | grep -i "X-OWA-Version"
< X-OWA-Version: 15.0.1497.26
```

The OWA-Version Header provides the Short Build Number of Exchange used by the target.

=> Providing theses results in a Wapiti scan would be awesome :).

**Comment by fwininger** [comment]
This issue will be addressed directly on wappalyzer

**Comment by fwininger** [comment]
https://github.com/AliasIO/wappalyzer/issues/5329
