### ISSUE TITLE
Module loading

### ISSUE THREAD

**Issue by bretfourbe** [wapiti-scanner/wapiti#212]
Currently, all attack modules are loaded by wapiti , which means instanciated with their `__init__` method, even if some modules are not required / not specified in the command line option `-m`.
What about loading only required attack modules ? This will allow to run modules separately, especially if a module is broken wapiti will remain usable with other modules.

**Comment by devl00p** [comment]
Related MR (currently in draft) https://github.com/wapiti-scanner/wapiti/pull/213

**Comment by devl00p** [comment]
Removed Draft status
