### ISSUE TITLE
Améliorer la gestion des jetons CSRF pour prendre en compte les jetons custom

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#259]
## Problème

Lors d'un scan de site web sur un site qui est fait maison, et qui utilise des tokens CSRF "maison", on ne reconnaît pas le tout.

Cela génère des faux positifs.

## Comportement attendu

Considérer les jetons "maison" qui contiennent le mot-clé CSRF, en majuscule ou en minuscule, comme valides.

## Détails

Exemples de jetons CSRF qui ont posé problème récemment :

```
__csrf_token__
CSRFKey
```

**Comment by fwininger** [comment]
On n'aura pas le temps de voir pour ceci. @bretfourbe tu as de la bande passante pour regarder ?

**Comment by tarraschk** [comment]
@bretfourbe @fwininger : j'ai fait une PR
