### ISSUE TITLE
Use Wapiti 3.1.0 within " wapiti -m shterm -u https://10.32.3.181/

### ISSUE THREAD

**Issue by zhouqingtao2006** [wapiti-scanner/wapiti#266]
I want to test all the modules and do not need to pass a parameter to module but it cann't work.
![image](https://user-images.githubusercontent.com/52315100/155450219-a275b3ca-c47f-4d45-ab15-f0183d34433f.png)
give a root module,still not pass
![image](https://user-images.githubusercontent.com/52315100/155449933-3e93eac8-3116-45af-9037-de9b53ac4d13.png)
want to list all modules, still not work.
![image](https://user-images.githubusercontent.com/52315100/155450135-d1e78af8-8af5-49a7-a7ae-7286601c46f7.png)

**Comment by bretfourbe** [comment]
Hi @zhouqingtao2006, if you want to list the available modules you just need to run `wapiti --list-modules` without specifying an url.
If you want to run the `blindsql` module only for instance : `wapiti -m blindsql -u your_target_url_here`. But by default, if you do not specify any module, wapiti will run default modules which are the following :
`cookieflags`, `csp`, `exec`,`file`, `http_headers`, `permanentxss`, `redirect`, `sql`, `ssl`, `ssrf` and `xss`.

**Comment by zhouqingtao2006** [comment]
@bretfourbe Thank you very much.

**Comment by zhouqingtao2006** [comment]
@bretfourbe wapiti can work on linux but cann't work on windows. can add the supported platform to the readme.rst?
![image](https://user-images.githubusercontent.com/52315100/155672503-04a1606a-90aa-4038-b530-1da1ff428035.png)

**Comment by devl00p** [comment]
Indeed we must add something in the readme for that.

You can run wapiti on Windows but you must use WSL for that

**Comment by devl00p** [comment]
WSL is now mentionned in the install and readme files
