### ISSUE TITLE
Urls list

### ISSUE THREAD

**Issue by anasbousselham** [wapiti-scanner/wapiti#267]
Hi,
I explore your great tools and I have 2 questions:
How to make easy to scan a list string path to file containing a list of target URLs/hosts.
I do that with `for i in $(cat gau_clean.txt); do wapiti -u $i -m xss --skip-crawl --flush-session; done; `
And more details for using Db backend (mysql+asyncmy).
Thank you.

**Comment by devl00p** [comment]
Hello !

You can use the -s option to pass a file containing URLs (one URL per line)

Wapiti is currently not ready for using other DB backends at the moment. Such development was started but it was paused as each DB treat encoding differently and requires a lot of work in our code.

**Comment by anasbousselham** [comment]
Thank you for your response however when I use -s urls.txt I have this error `wapiti: error: one of the arguments -u/--url --list-modules --update is required` . I'm confused .
Thanks

**Comment by deadjdona** [comment]
> Thank you for your response however when I use -s urls.txt I have this error `wapiti: error: one of the arguments -u/--url --list-modules --update is required` . I'm confused . Thanks

use --url with first domain.

**Comment by devl00p** [comment]
Thank you @deadjdona :)

Closing the issue
