### ISSUE TITLE
Unable to import module ssl

### ISSUE THREAD

**Issue by beruhan** [wapiti-scanner/wapiti#268]
![image](https://user-images.githubusercontent.com/7598892/156573053-e6328d36-1ed8-4c6c-96ce-f161635b4f51.png)

**Comment by bretfourbe** [comment]
Hi @beruhan, you might need to install extras (sslyze) to use `ssl` module. From `setup.py` :
![image](https://user-images.githubusercontent.com/27951656/156579122-a0a85acd-8b7b-49b9-8ca4-1549edb9d845.png)

**Comment by beruhan** [comment]
ok,thanks!

**Comment by Mistic92** [comment]
Hi, how to install extras when running in Docker built from Dockerfile in repo?
