### ISSUE TITLE
can wapiti support python3.6

### ISSUE THREAD

**Issue by beruhan** [wapiti-scanner/wapiti#269]
I install wapiti on python3.6 successfully.But It can't run,has anyway to run it successfully?
![image](https://user-images.githubusercontent.com/7598892/156576566-ba41dc49-7cf4-4304-8dde-f64136011633.png)

**Comment by bretfourbe** [comment]
Since wapiti use `asyncio` it requires at least python3.7

**Comment by devl00p** [comment]
Indeed the Python version requirements is described in the README
