### ISSUE TITLE
Wapiti scan for non query-string URLs 

### ISSUE THREAD

**Issue by hczdmr** [wapiti-scanner/wapiti#271]
Hello,

When I scan this URL (https://abc.com/abc), Wapiti adds payloads (?PAYLOAD) end of the URL but not adding without ? character. 
Can it scan both with and without question mark character?  If you want, we can develop this feature too.

Current situation: https://abc.com/abc?PAYLOAD
Expectation: https://abc.com/abcPAYLOAD

Sincerely.

**Comment by bretfourbe** [comment]
Hi @hczdmr, do you mean on the crawling step such as a fuzzing scan or on attack modules ?

**Comment by hczdmr** [comment]
on attack modules. For example: wapiti -u "https://abc.com/abc" -m xss:post --flush-attacks --flush-session --no-bugreport --scope url

**Comment by hczdmr** [comment]
Hi @bretfourbe, Is there any update?

**Comment by devl00p** [comment]
Currently we do not plan to inject data outside of POST data or query strings. We still have a lot of work on supporting JSON and XML for attacks so I'm closing the issue.
