### ISSUE TITLE
Exceptions lors de certains scans web

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#273]
Salut @devl00p on a rencontré un souci lors de certains scans de sites web récents.

Le souci en question est une exception, décrite ci-dessous :

![image](https://user-images.githubusercontent.com/4974759/159910707-895c892d-b43d-49d8-89ce-0f1b9948bed7.png)

Pour le contexte, cela semble se produire lors de certains scans authentifiés.

Peux-tu nous aider stp ?

**Comment by fwininger** [comment]
J'ai mis à jour le screen avec la bonne erreur :)

**Comment by bretfourbe** [comment]
Peut-être que cela vient de là : https://github.com/encode/httpx/issues/2139

**Comment by tarraschk** [comment]
@devl00p pour info j'ai un exemple d'URL où nous rencontrons le souci, je te l'envoie par email si ça peut aider pour reproduire / identifier le souci

**Comment by devl00p** [comment]
A ce que j'ai pu remarquer:

- ça ne concerne pas uniquement les sites avec authentification
- le correctif poussé sur httpx ne règle pas le problème
- ça peut arriver même sans utilisation d'un module de scan. En fait on peut réécrire `Wapiti.attack` sous le forme suivante et le bug apparaîtra encore: 

```python
    async def attack(self, stop_event: asyncio.Event):
        """Launch the attacks based on the preferences set by the command line"""
        await self.crawler.close()
        await self.persister.close()
        return
```
Le problème semble donc lié aux méthodes `Wapiti.browse` et `Explorer.async_explore`.

Une piste possible est l'utilisation du mode stream car le souci semble disparaître si on change l'instruction suivante dans `crawler.py`:

```python
self._crawler.stream = True
```

Snippet pour reproduire cela:

```python
import asyncio
import httpx

async def main():
    timeout = 10
    client = httpx.AsyncClient(timeout=timeout)
    use_stream = True

    for url in [
        "http://httpbin.org/"
    ]:
        request = client.build_request("GET", url, timeout=timeout)
        try:
            response = await client.send(
                request,
                stream=use_stream
            )
        except Exception as ex:
            print(type(ex), repr(ex))
        else:
            print(response)

    await client.aclose()

if __name__ == "__main__":
    asyncio.run(main())
```

Ce code provoque l'erreur mais fonctionne correctement si `use_stream` est mis à `False`

A déterminer si notre utilisation du mode `stream` est mauvaise ou si c'est un bug de httpx/httpcore.

**Comment by tarraschk** [comment]
@devl00p merci pour ton retour

As-tu besoin d'éléments en plus de notre part ?

**Comment by tarraschk** [comment]
Salut @devl00p apparemment nous avons toujours le problème : 

```
# ujson module not found, using json
# msgpack not installed, MsgPackSerializer unavailable
# Traceback (most recent call last):
#   File "/usr/local/bin/wapiti", line 33, in <module>
#     sys.exit(load_entry_point('wapiti3==3.1.1', 'console_scripts', 'wapiti')())
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.1.1-py3.9.egg/wapitiCore/main/wapiti.py", line 1423, in wapiti_asyncio_wrapper
#     asyncio.run(wapiti_main())
#   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
#     return loop.run_until_complete(main)
#   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
#     return future.result()
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.1.1-py3.9.egg/wapitiCore/main/wapiti.py", line 1410, in wapiti_main
#     await wap.attack(global_stop_event)
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.1.1-py3.9.egg/wapitiCore/main/wapiti.py", line 605, in attack
#     await self.crawler.close()
#   File "/usr/local/lib/python3.9/dist-packages/wapiti3-3.1.1-py3.9.egg/wapitiCore/net/crawler.py", line 614, in close
#     await self.client.aclose()
#   File "/usr/local/lib/python3.9/dist-packages/httpx-0.22.0-py3.9.egg/httpx/_client.py", line 1946, in aclose
#     await self._transport.aclose()
#   File "/usr/local/lib/python3.9/dist-packages/httpx-0.22.0-py3.9.egg/httpx/_transports/default.py", line 365, in aclose
#     await self._pool.aclose()
#   File "/usr/local/lib/python3.9/dist-packages/httpcore-0.14.7-py3.9.egg/httpcore/_async/connection_pool.py", line 312, in aclose
#     raise RuntimeError(
# RuntimeError: The connection pool was closed while 2 HTTP requests/responses were still in-flight.
```

As-tu besoin d'éléments en plus de notre part ?

**Comment by tarraschk** [comment]
ping @devl00p stp :)

**Comment by devl00p** [comment]
@tarraschk Je ne suis pas parvenu à reproduire de mon côté

Je veux bien avoir la ligne de commande utilisée ainsi que l'output de `pip freeze`

**Comment by tarraschk** [comment]
@devl00p merci pour ton retour !

J'ai regardé avec @fwininger et les tests sont faits via https://hub.docker.com/r/cyberwatch/wapiti qui est généré à partir du Dockerfile du repo ( https://github.com/wapiti-scanner/wapiti/blob/master/Dockerfile )

Pour la ligne de commande, je t'envoie ça par mail

**Comment by tarraschk** [comment]
Commandes envoyées par email @devl00p . Comme dit dans mon mail, on aimerait soit trouver comment résoudre le problème, soit faire en sorte qu'un crash de ce type n'impacte pas tout le scan mais uniquement le test d'attaque fautif, de sorte à pouvoir continuer le scan et à pouvoir aussi récupérer les résultats.

**Comment by devl00p** [comment]
La dernière release de httpcore qui est utilisée dans la dernière version de Wapiti devrait régler le problème : https://github.com/encode/httpcore/releases/tag/0.16.3
