### ISSUE TITLE
ModuleNotFoundError: No module named 'sqlalchemy.ext.asyncio'

### ISSUE THREAD

**Issue by ovhx** [wapiti-scanner/wapiti#276]
Title explains it

**Comment by bretfourbe** [comment]
Hi @ovhx, can you give some more context please ?
@devl00p do you think we should add asyncio extra dependency from sqlalchemy ?

**Comment by ovhx** [comment]
> Hi @ovhx, can you give some more context please ? @devl00p do you think we should add asyncio extra dependency from sqlalchemy ?

Well I ran "sudo python3 setup.py install" and then run the binary and this happened

**Comment by ovhx** [comment]
any updates

**Comment by bretfourbe** [comment]
HI @ovhx, can you try `pip install sqlalchemy[asyncio]` ? Let me know if this works for you.

**Comment by ovhx** [comment]
I am getting the same result.

Traceback (most recent call last):
  File "/home/ovh/tools/wapiti/bin/./wapiti", line 31, in <module>
    from wapitiCore.main.wapiti import wapiti_asyncio_wrapper
  File "/home/ovh/tools/wapiti/wapitiCore/main/wapiti.py", line 50, in <module>
    from wapitiCore.net.sql_persister import SqlPersister
  File "/home/ovh/tools/wapiti/wapitiCore/net/sql_persister.py", line 28, in <module>
    from sqlalchemy.ext.asyncio import create_async_engine
ModuleNotFoundError: No module named 'sqlalchemy.ext.asyncio'

**Comment by ovhx** [comment]
> pip install sqlalchemy[asyncio]
Requirement already satisfied: sqlalchemy[asyncio] in /usr/local/lib/python3.9/dist-packages (1.3.23)
WARNING: sqlalchemy 1.3.23 does not provide the extra 'asyncio'
  
thats the installation output

**Comment by bretfourbe** [comment]
@ovhx it seesms you have an old sqlalchemy version, latest is 1.4.35. Can you try running the wapiti installation in a fresh python virtualenv ?

**Comment by devl00p** [comment]
both setup.py and Pipfile use sqlalchemy = ">=1.4.26" as requirements.

You should indeed use a virtual environment and use `python setup.py install` to get all the required dependencies
