### ISSUE TITLE
Sslyze module

### ISSUE THREAD

**Issue by anasbousselham** [wapiti-scanner/wapiti#279]
Hi,
I have this error `Unable to import module ssl` however I have already installed.

![image](https://user-images.githubusercontent.com/9357948/162471362-c773d6a1-e790-4ffd-a523-8bf3250f883b.png)

**Comment by bretfourbe** [comment]
HI @anasbousselham, can you have a look at https://github.com/wapiti-scanner/wapiti/issues/268 please ?

**Comment by anasbousselham** [comment]
already installed sslyze and work perfectly with python3 but not with wapiti3

**Comment by jhammons** [comment]
You need to also install humanize.

**Comment by devl00p** [comment]
Hey @anasbousselham !

How did you install Wapiti ? using pip or your system package provider or git clone ?

Can you provide the output if the `pip freeze` command in this environment ?

Regards

**Comment by devl00p** [comment]
Dependencies should be all good with the new release, 3.1.5, closing
