### ISSUE TITLE
does any way to disable store session 

### ISSUE THREAD

**Issue by beruhan** [wapiti-scanner/wapiti#280]
I don't want store session,I used --flush-session command parameter, but I found wapiti also store data in /root/.wapiti/scans,Can any way to prevent it?

**Comment by bretfourbe** [comment]
Hi @beruhan,
The `--store-session` option allows to specify where the session files are stored, but those files are required by Wapiti. As you noticed it, we do not delete them after the end of the execution. So no, there is no way at the moment, but i suppose it could be an improvement. @devl00p 
What i can suggest you for now is to set the `store-session` and the `store-config` options with specific directories and then delete the generated directories when you no longer need them.
