### ISSUE TITLE
Restreindre le HSTS aux seuls ports HTTPS sur mod_http_headers

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#282]
Le module http_headers teste la présence d'un header HSTS sur tous les ports web

Or, d'après https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#description on a :

```
The Strict-Transport-Security header is ignored by the browser when your site is accessed using HTTP; this is because an attacker may intercept HTTP connections and inject the header or remove it. When your site is accessed over HTTPS with no certificate errors, the browser knows your site is HTTPS capable and will honor the Strict-Transport-Security header. 
```

Le test du HSTS sur un port HTTP ne sert donc à rien. Il faut le tester que sur un port HTTPS.

A la place, la partie intéressante à tester sur un port HTTP est la redirection vers HTTPS, avec un 301, conformément à https://github.com/wapiti-scanner/wapiti/issues/118

**Comment by un-fmunozs** [comment]
I would add that even on a redirection testing for the HSTS header on HTTP I think its considered useless. as @tarraschk mentioned, HSTS must be ignored by browsers when the site is accessed using plain HTTP.

**Comment by devl00p** [comment]
Interesting :thinking: 

Microsoft did not get the information

```$ curl -I http://microsoft.com/
HTTP/1.1 301 Moved Permanently
Date: Fri, 07 Oct 2022 15:18:56 GMT
Server: Kestrel
Location: https://www.microsoft.com/
Strict-Transport-Security: max-age=31536000; includeSubDomains
```

but youtube does it the right way
