### ISSUE TITLE
wapiti never Finish when crawled as mjpg url

### ISSUE THREAD

**Issue by beruhan** [wapiti-scanner/wapiti#291]
I used wapiti to test a video website,It never Finished。Finally，I fund one url is a dynamic mjpeg video stream which cause wapiti never finished。How to handle this problem? 
![image](https://user-images.githubusercontent.com/7598892/175499306-9ed7afc5-03a8-4772-87eb-c86af4c76d11.png)

**Comment by devl00p** [comment]
Hello ! Indeed this is a known issue :-/ 

We do not plan to limit the size of downloaded content in the crawler as it implies a lot of uncertainty on Wapiti behavior. At least you can use the `-x` option to prevent Wapiti from crawling the problematic URL

Regards
