### ISSUE TITLE
Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by rimiti** [wapiti-scanner/wapiti#293]
Hello,

Thanks for your awesome pacakge.

When I try to launch a simple default scan, I'm getting below error:

```
Error -3 while decompressing data: incorrect header check
```

How to reproduce:

```sh
git clone git@github.com:wapiti-scanner/wapiti.git
cd wapiti
python -m venv wapiti3
. wapiti3/bin/activate
python3 setup.py install
python ./bin/wapiti
python ./bin/wapiti -u https://www.wesite.com
```

**Question:**

Do you know how to resolve this issue?

Thanks,

**EDIT:**

After moving below lines from the **setup.py** file (block **extras_require** into the **install_requires**) this error doesn't appear anymore:

```
  "sslyze==5.0.0",
  "humanize==3.13.1"
```

**Comment by devl00p** [comment]
Indeed current developments on the repository introduced that bug.

It is in fact relation to decompression of responses body, you may had more luck after you changed some stuff but it was in fact not related.

**Comment by rimiti** [comment]
Ok, thank you for your answer.
