### ISSUE TITLE
Analyse des technologies : passer à l'approche par analyse JS

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#303]
Un reminder pour qu'on se souvienne de passer à l'approche JS pour l'identification des technologies, plutôt que de faire ça par regexp, lorsque c'est possible.

Cela donnera de bien meilleurs résultats au moins sur jQuery et Bootstrap !

Nécessite de finir d'abord la partie moteur JS de Nicolas.

**Comment by devl00p** [comment]
Je ferme l'issue qui est résolue par l'utilisation de firefox headless et son utilisation dans le module wappalyzer
