### ISSUE TITLE
Crashes when exporting to JSON with --detailed-report flag

### ISSUE THREAD

**Issue by undergroundwires** [wapiti-scanner/wapiti#309]
Thank you for building and maintaining fast, easy-to-use and useful tool.

The problem is reproducible using:

```sh
wapiti --url https://github.com --format json --scope page --detailed-report --output wapiti-report.json
```

Error:

`TypeError: Object of type bytes is not JSON serializable`

**Comment by devl00p** [comment]
Thank you for the issue, I will take a look
