### ISSUE TITLE
Page url attribute is inconsistent with other Page attributes

### ISSUE THREAD

**Issue by hezanathos** [wapiti-scanner/wapiti#31]
This class https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/net/crawler.py#L116 has an url attribute.
```py
class Page:
    def __init__(self, response: Response, url: str, empty: bool = False):
        """Create a new Page object.
        @type response: Response
        @param response: a requests Response instance.
        @type url: str
        @param url: URL of the Page.
        @type empty: bool
        @param empty: whether the Page is empty (body length == 0)"""
        self._response = response
        self._url = url
        self._base = None
        self._soup = None
        self._is_empty = empty

    @property
    def url(self) -> str:
        """Returns the URL of the current Page object
        @rtype: str
        """
        return self._url
```

It is for example used here : 
https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/net/crawler.py#L1185
```py
  return Page(response, resource.url)
```

response is here the object returned by a request.get, such an object has an url attribute. This url attribute can be different from the resource.url. In particular it follows redirections. This means that when you want to get the page url when you were redirected after a get, you currently have to use `page._request.url`. Such usage of a private parameter is probably not what we want.

The other problem is that the properties of a page object when redirected are the properties of the last get, so it could lead to think that some url responds in some way when in fact it redirects.

Should we change the page url attribute to use the response.url instead of a value sent during initialisation ? Or have a second attribute for that ? 

If I am missing something else feel free to explain it to me as I am discovering the project.

**Comment by devl00p** [comment]
Hello,

I understand your point of view. Most of the time, Wapiti send HTTP requests without following the redirection, just extracting the `Location` header but I think it would be ok to return the new URL if we allowed redirects.

For this behavior we could add a new attribute on `Page` to leverage the `requests` `history` attribute.
