### ISSUE TITLE
Could not find a version that satisfies the requirement mitmproxy==8.0.0

### ISSUE THREAD

**Issue by LewisWildgoose** [wapiti-scanner/wapiti#315]
https://i.imgur.com/egN4Ugh.png

Can't seem to install due to this error, thank you.

**Comment by devl00p** [comment]
Hello @LewisWildgoose ! We had to integrate mitmproxy for the man in the middle and headless browser modes.

Unfortunately mitmproxy doesn't support python 3.7 so we had to remove it to.

It should work with Python >= 3.8

Regards
