### ISSUE TITLE
Consider Putting a Wholesome Command

### ISSUE THREAD

**Issue by ivan-sincek** [wapiti-scanner/wapiti#32]
Hi,

Please consider putting a wholesome command in the [execPayloads.txt](https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/config/attacks/execPayloads.txt) file while testing for command injections.

For example, simply copy the `set` command:

```
...
&set&
set
/e\0
...
```

Because, Wapiti fails to detect a very basic command injection like this one:

```php
<form method="post" action="#">
	<input name="cmd" type="text">
</form>
<?php
	if (isset($_POST["cmd"])) {
		echo "<pre>" . shell_exec($_POST["cmd"]) . "</pre>";
	}
?>
```

I understand that chances for this piece of code to be in the wild nowadays are very slim and if I misunderstood your goal, please close this issue.

PHP script was tested on XAMPP for Windows v7.4.3 (64-bit) with PHP v7.4.3.

Wapiti was tested on both Windows 10 Pro OS (64-bit) and Kali Linux 2020.3 (64-bit).

Keep up the good work!

Best regards,
Ivan.

**Comment by tarraschk** [comment]
Hello @ivan-sincek, thank you for your message.

@devl00p what do you think? We also noticed that the SQL injection engine should be improved.

On our side we are focusing on adding a versions + CVEs assessment feature to Wapiti, but would this SQLi improvement be easy to do?

Best regards

**Comment by devl00p** [comment]
I'm ok with adding a simple command without any other character.
We also need to add `|env` (I'm arleady using it locally).

Yes the current SQL injection modules are currently error-based and time-based only.

Having a boolean-based module would be the way to fix this I guess.
