### ISSUE TITLE
Payloads using [FILENAME] should not be used if the targeted request doesn't have a filename

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#34]
Problem:

If the target URL is `http://target/?p=home`  then the URL doesn't have a filename (compared to for example `http://target/index.php`) and payloads having a `[FILENAME]` placeholder should not be used on that target URL.

Example with file handling payloads : 

```
[local_current_file_with_ads]
payload = [FILE_NAME]::$DATA
rules = <?php
messages = Possible source code disclosure
```

With the previous example, this payload should be ignored as we don't want to test the URL `http://target/?p=::$DATA` (I can't see realistic scenarios, other modules/payloads certainly have the same issue)

**Comment by bretfourbe** [comment]
Did it already happen on a concrete case ?
When i try this command : 
`./bin/wapiti -u http://testphp.vulnweb.com/index.toto?p=home -m file --color -f html -o output-report --store-session=sessions/ --flush-session -v 2 --scope=url`
i have the FILE_NAME payloads launched :
`[¨] GET http://testphp.vulnweb.com/index.toto?p=index.toto (0)`
`[¨] GET http://testphp.vulnweb.com/index.toto?p=index.toto%00 (0)`
`[¨] GET http://testphp.vulnweb.com/index.toto?p=index.toto%3A%3A%24DATA (0)`
But with the following command i have not :
`./bin/wapiti -u http://testphp.vulnweb.com/?p=home -m file --color -f html -o output-report --store-session=sessions/ --flush-session -v 2 --scope=url`
Futhermore, in mutate() defined in attack.py (which is called in mod_file.py), it appears to be already checked :
![image](https://user-images.githubusercontent.com/27951656/93447628-e6f72a80-f8d2-11ea-806f-95550902b2d8.png)

**Comment by devl00p** [comment]
Hmm I guess I must have fixed this in july but didn't remember :laughing:

**Comment by bretfourbe** [comment]
Here : https://github.com/wapiti-scanner/wapiti/commit/5ac40468447a425710b8fb5fb24bd109c852aec3
