### ISSUE TITLE
The specified module cannot be found

### ISSUE THREAD

**Issue by purple-WL** [wapiti-scanner/wapiti#365]
After operation, the display is as follows:

Wapiti 3.1.5 (wapiti-scanner.github.io)
[!] Unable to import module takeover
[!] Unable to import module ssl
[!] Unable to import module log4shell
[!] Unable to find a module named ssl

**Comment by devl00p** [comment]
Hello ! I will look at that.

Did you installed it using `pip install wapiti3` or using git ?

Regards

**Comment by purple-WL** [comment]
> Hello ! I will look at that.
> 
> Did you installed it using `pip install wapiti3` or using git ?
> 
> Regards

Use git to download and install the source code, and directly execute it in the bin directory. The system is macOS

**Comment by devl00p** [comment]
You need to use `pip install 'wapiti3[sslyze]'` to have requirements for the ssl module but I can't tell for the other errors

**Comment by devl00p** [comment]
Ok thank for the information

**Comment by devl00p** [comment]
I wasn't able to reproduce the issue but I don't have macOS system.

Can you post the output of `pip freeze` when you are in the virtual env ?

Here is mine so we can compare:

```
aiocache==0.11.1
aiohttp==3.8.1
aiosignal==1.3.1
aiosqlite==0.17.0
anyio==3.6.2
arsenic==21.8
asgiref==3.5.2
async-timeout==4.0.2
attrs==22.2.0
beautifulsoup4==4.11.1
Brotli==1.0.9
browser-cookie3==0.16.2
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
cryptography==38.0.4
dnspython==2.1.0
Flask==2.2.2
frozenlist==1.3.3
greenlet==2.0.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==0.16.3
httpx==0.23.3
hyperframe==6.0.1
idna==3.4
importlib-metadata==6.0.0
itsdangerous==2.1.2
jaraco.classes==3.2.3
jeepney==0.8.0
Jinja2==3.1.2
kaitaistruct==0.10
keyring==23.13.1
ldap3==2.9.1
loguru==0.6.0
lz4==4.3.2
Mako==1.2.4
MarkupSafe==2.1.1
mitmproxy==9.0.0
mitmproxy_wireguard==0.1.20
more-itertools==9.0.0
msgpack==1.0.5rc1
multidict==6.0.4
passlib==1.7.4
pbkdf2==1.3
protobuf==4.21.12
publicsuffix2==2.20191221
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.21
pycryptodome==3.16.0
pyOpenSSL==22.1.0
pyparsing==3.0.9
pyperclip==1.8.2
rfc3986==1.5.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
SecretStorage==3.3.3
six==1.16.0
sniffio==1.3.0
socksio==1.0.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
SQLAlchemy==2.0.0rc3
structlog==20.2.0
tld==0.12.6
tornado==6.2
typing_extensions==4.4.0
urwid==2.1.2
wapiti3==3.1.5
Werkzeug==2.2.2
wsproto==1.2.0
yarl==1.8.2
yaswfp==0.9.3
zipp==3.11.0
zstandard==0.18.0
```

**Comment by devl00p** [comment]
I'm closing the issue as it dates from january. Some logs were added in Wapiti to give more details about module import errors.

Get the latest version from the repository and try again
