### ISSUE TITLE
Error 502 - Bad Gateway with self signed certificate in headless mode

### ISSUE THREAD

**Issue by Darkiros** [wapiti-scanner/wapiti#366]
An Error 502  is reached when you scan a website with a self signed certificate in headless mode.

To correct it, I suggest to put `,ssl_insecure=True` in https://github.com/wapiti-scanner/wapiti/blob/d42726e829a6933db8e2b1a6b548bd48ad64495b/wapitiCore/net/intercepting_explorer.py#L203

**Comment by bretfourbe** [comment]
Fix by #367
