### ISSUE TITLE
Report Full HTTP Request and Response

### ISSUE THREAD

**Issue by mydeadlyvenoms** [wapiti-scanner/wapiti#37]
To better understand an issue it would be great if the final report contains the **full** HTTP request **and** response.
This would be great a feature to better understand and help fixing found issues within an application.

**Comment by devl00p** [comment]
Hello,

Yes I understand your point of view but responses can be very big sometimes and it may generate huge reports that can't be loaded correctly within the browser.

I think we can at least put some kind of snippets inside the report to show (for example) which pattern was found to detect the vulnerability.

For example with a file inclusion vulnerability the snippet would be the X (maybe 500) first characters of `/etc/passwd` or error messages for the sql attack module.

**Comment by mydeadlyvenoms** [comment]
Hi @devl00p thank you very much for the detailed response. I absolutely see your point. 

However, many other security scanners still provide such a feature. Maybe we can add an additional flag that allows users to define if they would like to have the full response within the final report? This will prevent bloated or broken HTML reports for users that are not interested in the HTTP response anyway. Another option would be to e.g., Base64 encode the HTML response. I guess w3af and Burp Suite have this feature implemented.

What do you think?

**Comment by cost6** [comment]
Any news on this enhancement? A flag to report full HTTP request and response pairs would be very much appreciated.
