### ISSUE TITLE
ConnectError http://127.0.0.1:8083

### ISSUE THREAD

**Issue by gornati5ci** [wapiti-scanner/wapiti#371]
Hello, I'm running Wapiti 3.1.6 on Window Subsystem for Linux.
I have an IIS server with Php manager installed. Php 8.1.14. There is a website configured on port 8083. I can reach it with my web browser(Chrome) without any problem.
Trying to execute the command wapiti -v2 -u http://127.0.0.1:8083 i get this output
ujson module not found, using json

 ██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗██████╗
 ██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║╚════██╗
 ██║ █╗ ██║███████║██████╔╝██║   ██║   ██║ █████╔╝
 ██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║ ╚═══██╗
 ╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║██████╔╝
  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝╚═════╝
Wapiti 3.1.6 (wapiti-scanner.github.io)
[+] GET http://127.0.0.1:8083/ (0)
[!] ConnectError with URL http://127.0.0.1:8083/
[*] Saving scan state, please wait...
This scan has been saved in the file /home/gianlucag/.wapiti/scans/127.0.0.1_8083_folder_4e6bdd8d.db
[*] Wapiti found 0 URLs and forms during the scan
[*] Existing modules:
         backup, brute_login_form, buster, cookieflags, crlf, csp, csrf, drupal_enum, exec, file, htaccess, htp, http_headers, log4shell, methods, nikto, permanentxss, redirect, shellshock, sql, ssl, ssrf, takeover, timesql, wapp, wp_enum, xss, xxe
[!] Unable to import module ssl
[!] Unable to find a module named ssl

[*] Launching module csp

[*] Launching module redirect

[*] Launching module file

[*] Launching module cookieflags

[*] Launching module exec

[*] Launching module http_headers

[*] Launching module xss

[*] Launching module ssrf
[*] Asking endpoint URL https://wapiti3.ovh/get_ssrf.php?session_id=8yi3kz for results, please wait...

[*] Launching module sql

[*] Launching module permanentxss

[*] Generating report...
A report has been generated in the file /home/gianlucag/.wapiti/generated_report
Open /home/gianlucag/.wapiti/generated_report/127.0.0.1_8083_02082023_1046.html with a browser to see this report.

Wsl is installed via Windows Powershell with admin rights. The command used was wsl --install. It has installed Ubuntu. Python is the default one, version 3.10.6.

Any suggestion on what could be the problem?
The same thing appens with http://localhost:8083 instead of http://127.0.0.1:8083

**Comment by devl00p** [comment]
Using the shell from WSL can you access the website using curl or wget ?

**Comment by devl00p** [comment]
Hello,

No it doesn't update itself, you can just update the data used by some modules with the --update option
Indeed we fixed a bug related to ports in URLs but it was only tied to standard ports.

I will close the issue
Regards
