### ISSUE TITLE
Add support for uncommon http methods

### ISSUE THREAD

**Issue by juansec** [wapiti-scanner/wapiti#374]
This is an idea, not a current issue:

It would be nice if it is possible to change the default GET/POST HTTP methods to uncommon methods such as PUT, DELETE, etc.

Benefits:

- It would be useful for API testing

**Comment by devl00p** [comment]
Currently there is the `methods` module in Wapiti that performs an OPTIONS HTTP request to see if uncommon methods like PUT or DELETE are allowed. It may satisfy your needs but it won't work if the server doesn't support OPTIONS.

I think the module could be improved to check OPTIONS first then attempt PUT based on what the response was.
