### ISSUE TITLE
Error when specifying a port in an URL

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#376]
I noticed that the scan doesn't work when a port is specified in an URL.

For example a wapiti scan on 'http://testphp.vulnweb.com/' finds 76 urls while the same scan on 'http://testphp.vulnweb.com:80/' finds only 1 url.

I checked Request#port and it has the right value (80 with both urls).

**Comment by fwininger** [comment]
@devl00p could you take a look ?

**Comment by devl00p** [comment]
I'm on it

**Comment by devl00p** [comment]
should be ok, closing the issue
