### ISSUE TITLE
dependency sslyze is not supported on ARM platforms

### ISSUE THREAD

**Issue by Dave3o3** [wapiti-scanner/wapiti#383]
Hi,

see [here](https://nabla-c0d3.github.io/sslyze/documentation/installation.html).

> SSLyze can be installed on the following platforms:
>
>    Windows 10 (64 bits)
>
>    macOS Big Sur
>
>    Linux (x86 and x86-64)
>
> Other platforms (such as ARM-based platforms) are not supported.

I think the issues with missing ssl module errors could come from users with those systems.

**Comment by devl00p** [comment]
Thank you for this information. I added some information to the README and FAQ files
