### ISSUE TITLE
Async_send modify the orginal request's headers by those of the response

### ISSUE THREAD

**Issue by Darkiros** [wapiti-scanner/wapiti#391]
Hello,
When you perform a request with some headers with the method `async_send` which is present in `crawler.py`, the orgial request's headers are edited with the headers of his response by this following code `request.set_headers(response.sent_headers)` line 395 in the same file (`crawler.py`). However, the response is returned.

Is it normal to modify the original request's headers with those of the response.request.headers ? 
And why are not the same ?

**Comment by devl00p** [comment]
We do that because Wapiti only defines some specific headers (mainly User-Agent) while common headers are added by `httpx`.

Here are some headers added by `httpx`:

```
host
connection
accept-language
accept-encoding
accept
```

Having the full headers really sent is useful when the report is generated along with the HTTP requests.
