### ISSUE TITLE
With the current options, we cannot have the "%" char in the login.

### ISSUE THREAD

**Issue by Slokilla** [wapiti-scanner/wapiti#396]
Quoting the wapiti man 

> - -a, --auth-cred
    Set credentials to use for HTTP authentication on the target (see available methods bellow). Given value should be in the form 
    login%password (% is used as a separator)

Let's suppose that my login is "99%OfCoffee", and my password "1%OfBrain". What would happen with the current CLI ? 

I suppose that the used login will be "99", and the used password "OfCoffee1%OfBrain". What a pity !

Can we provide more sophisticated options like "--login" and "--password" to provide both separately. This way, we keep supporting the old syntax, and we add support of "%" in logins.

**Comment by devl00p** [comment]
Good idea. I think  `--user` would be more meaningful that `--login`.

Also we should certainly name them `--auth-user` and `--auth-password` as we already have the `--auth-method` option. That way users whould not be mistaken with other credentials.

By the way the same should be done for `--form-cred`

**Comment by Slokilla** [comment]
I totally agree with your suggestion !
