### ISSUE TITLE
Dependency mismatch between pyproject.toml and setup.py in PyPi package

### ISSUE THREAD

**Issue by D3vil0p3r** [wapiti-scanner/wapiti#401]
[pyproject.toml](https://github.com/wapiti-scanner/wapiti/blob/master/pyproject.toml) has not `typing-extensions` dependency whereas [wapiti3-3.1.7.tar.gz](https://pypi.org/project/wapiti3/#files) has in `setup.py` on `install_requires`.

So, `typing-extensions` is needed or not?

**Comment by Darkiros** [comment]
Hi @D3vil0p3r thank you for your issue,
The `typing-extensions` is not in pyproject.toml because it is implicit.
There is another dependency that requires this module and therefore installs it.

**Comment by devl00p** [comment]
Closing the issue
