### ISSUE TITLE
CRLF module double encode URL

### ISSUE THREAD

**Issue by RMI78** [wapiti-scanner/wapiti#402]
I don't really know if this is made on purpose but when trying to test the CRLF module on the following page:
```PHP
<?php
if(isset($_GET['user-agent'])) {
  $user_agent = $_GET['user-agent'];
  // header() in php now prevent CRLF so here is a workaround
  $headers_arr = preg_split('/\r\n|\r|\n/', $user_agent);
  header_remove();
  header("User-Agent: $headers_arr[0]");
  if(count($headers_arr)>1){
    for($i=1;$i<count($headers_arr); $i++){
        header($headers_arr[$i]);
    }
  }
}
else{
  // Set the value of the "param" parameter to "blabla"
  $param_value = "blabla";
  $url = "index.php?user-agent=" . $param_value;

  // Redirect to the URL with the parameter
  header("Location: " . $url);
}
?>
<!DOCTYPE html>
<html>
<head>
	<title>CRLF Example</title>
</head>
    <body>
        <p>Page where you can do some injections into the user_agent param.</p>
    </body>
</html>
```

A CRLF is not recognized even though it is doable with curl when hitting:
```Bash
curl -v -G 'http://127.0.0.1:80/index.php' --data-urlencode 'user-agent=http://www.google.fr\r\nwapiti: 3.1.7 version'
```

With some debugging I tried to see the logs of the server to see the requests made by curl and wapiti. And it turned out that Wapiti double encode its payload. 
As a reminder: here is the payload Wapiti tries to inject (you can also find it above on my curl command):
``http://www.google.fr\r\nwapiti: 3.1.7 version``

Here is the GET request from wapiti logged by the server:
``index.php?user-agent=http%253A%2F%2Fwww.google.fr%250D%250Awapiti%253A%25203.1.7%2520version``
And the GET request made by curl:
``index.php?user-agent=http%3A%2F%2Fwww.google.fr%5Cr%5Cnwapiti%3A+3.1.7+version``

You can clearly see that the `:` is interpreted as `%253A` by Wapiti and `%3A` by curl, same goes for `/` characters and so on...
Investigating further, I modified my code the following way on the third line:
```PHP
$user_agent = urldecode($_GET['user-agent']);
```
This modification resulted in a normal behavior from Wapiti so we can be 100% sure it is a double encoding thing. You can clearly see that this behavior will mess around with the header function because of misinterpreted characters.

Don't hesitate to let me know if this is a real issue or if this is something intentional.

**Comment by tarraschk** [comment]
Hey @RMI78 I think that it's not something intentional, as double encoding might lead to false negative :).

Do you know if this only affects the CRLF module? Have you seen the same behaviour on the XSS module for example?

For me, it looks like the issue comes from the fact that we encode the payload through this line:
https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/attack/mod_crlf.py#L40

and then we encode it again when performing the attack

=> Could you try to see if it affects other modules?

=> Could you try to just remove the `quote` call here https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/attack/mod_crlf.py#L40 and run again the attack to see if it fixes the problem?

**Comment by tarraschk** [comment]
also pinging @bretfourbe @Darkiros and of course @devl00p :)

**Comment by devl00p** [comment]
This is clearly an issue. Maybe it came with the move from requests to httpx

**Comment by Slokilla** [comment]
If the problem comes from the switch from requests to httpx, will we have the same issue with other calls to `urllib.parse.quote`. There's several calls: 
![image](https://github.com/wapiti-scanner/wapiti/assets/51393687/0d2c266e-4555-4f6d-a3cb-6a3a4ae7dae9)

**Comment by tarraschk** [comment]
@Slokilla I think that if other modules were really impacted we would have seen this, at least for attacks like XSS were we have several controls that we run when releasing

However, double checking this would still be good for the maturity of the project

@RMI78 may you have a look at the other modules mentioned by @Slokilla when developing the new unit tests?

thanks!

**Comment by RMI78** [comment]
From the little I have seen, it seems that the permanentxss, the xxe and the ssrf modules are also touched by this issue but i'd like to do more tests with them to be really sure about that

**Comment by RMI78** [comment]
Little update on this issue. I've had the time to check all the modules @Slokilla mentioned, and it's safe to say that only the CRLF module was impacted by the double encoding thing. The issue may now be closed.
