### ISSUE TITLE
Buster module logs not in the report

### ISSUE THREAD

**Issue by RMI78** [wapiti-scanner/wapiti#406]
I have noticed that the buster module is not logging anything in the report (even in detailed mode). I have acknowledged that this module is more about discovering additionnal informations than finding vulnerabilities. That said we do have sections in the report regarding the additionnal informations and I can't see why we shouldn't add them up.

**Comment by devl00p** [comment]
Indeed this is something to fix. People may be interested in having the discovered paths in the logs too
