### ISSUE TITLE
how to generate csv file for scanned vulnerabilities

### ISSUE THREAD

**Issue by raghubetageri** [wapiti-scanner/wapiti#44]
@tarraschk  @hezanathos @jinxka @lotfree please create a csv report generator for scanned vulnerabilities.as i can see html,json,txt, but i couldn't find csv

**Comment by fwininger** [comment]
hello @raghubetageri thanks for the suggestion, can you propose a pull requests for this ?

**Comment by raghubetageri** [comment]
@fwininger i am beginner level i am still learning please make code to generate csv report

**Comment by raghubetageri** [comment]
I am learner please make a code to create a CSV format report

**Comment by devl00p** [comment]
Code pushed to master, feature will be available in next release. You can also use git clone to get it.
