### ISSUE TITLE
Improve Vulnerbilties report with WSTG code

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#47]
Hello,

Would it be possible to update the vulnerabilities part on the report so there will be one category per WSTG  code?

For example: 'SQL Injection' and 'Blind SQL Injection' should be merge as they both get WSTG-INPV-05 while 'Cross Site Scripting' should be divided by 'WSTG-INPV-02' and 'WSTG-INPV-01'

**Comment by devl00p** [comment]
Hello,

Sure, the vulnerability can be reported as "sql injection" and the fact that it is blind-based can be mentionned in the description for example.
