### ISSUE TITLE
attack.py used as a module

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#477]
Just noticed this when testing `-m all` for the new release:

`[*] Launching module attack`

While this is not a significant problem, it should not happen. I wonder when that bug was introduced :thinking:

**Comment by devl00p** [comment]
seems related to a module not overwriting its `name` attribute. I'm on it

**Comment by bretfourbe** [comment]
indeed, there is no `name` overwriting in spring4shell module
