### ISSUE TITLE
Doc incohérente pour l'installation

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#486]
Salut,

la doc dit que pour installer à partir du code courant Wapiti, il faut faire `python setup.py install`

Or, ça ne marche pas :-D

Et il semblerait que la doc ne soit pas à jour

Peux-tu regarder @Darkiros 

Merci !

**Comment by bretfourbe** [comment]
Fixed by https://github.com/wapiti-scanner/wapiti/pull/487
