### ISSUE TITLE
Migrer la reconnaissance des hashs Drupal vers les Hashs de Git

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#491]
Salut,

suite à tes travaux sur HashThePlanet (https://github.com/Cyberwatch/HashThePlanet/pull/36) peux-tu migrer les algos de hachage du module DrupalEnum vers les hachage de Git plutôt que sha256 (https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/attack/mod_drupal_enum.py#L39) ?

Il faudra aussi modifier le fichier des technos (https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/data/attacks/drupal_hash_files.json)

Merci !

**Comment by bretfourbe** [comment]
Fixed by https://github.com/wapiti-scanner/wapiti/pull/495
