### ISSUE TITLE
Faire un module d'énumération générique par hash

### ISSUE THREAD

**Issue by tarraschk** [wapiti-scanner/wapiti#493]
Une fois que #491 et #492 seront traités, pourras-tu faire un module générique d'énumération par hash, qui prendra des paramètres listant les technologies souhaitées, et permettra de rassembler en un module les énum de Drupal et Joomla, et d'en ajouter facilement d'autres si besoin plus tard ?

**Comment by bretfourbe** [comment]
Done with : https://github.com/wapiti-scanner/wapiti/pull/515
