### ISSUE TITLE
wapp module issues 

### ISSUE THREAD

**Issue by zero13ro** [wapiti-scanner/wapiti#501]
[*] Launching module wapp
TypeError 'NoneType' object is not subscriptable
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 390, in attack
    original_request_or_exception = next(generator)
                                    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wapitiCore/attack/mod_wapp.py", line 76, in attack
    application_data = ApplicationData(os.path.join(self.user_config_dir, self.WAPP_DB))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wapitiCore/wappalyzer/wappalyzer.py", line 46, in __init__
    self.applications = obj["technologies"]
                        ~~~^^^^^^^^^^^^^^^^
Wapiti 3.0.4. Requests 2.23.0. OS linux
Error sending crash report

**Comment by fwininger** [comment]
@bretfourbe can you take a look ?

**Comment by zero13ro** [comment]
sorry guys, noticed after a couple of hours that the version installed from kali repo (apt install) is 3.0.4 but you latest build is 3.1.8.
I have uninstalled the one from kali and installed the latest one. I can confirm the module is working.

**Comment by fwininger** [comment]
Thanks!

**Comment by zero13ro** [comment]
but on the latest version, you can have a look on this module error

Wapiti 3.1.8 (wapiti-scanner.github.io)
[*] You are lucky! Full moon tonight.
[*] Saving scan state, please wait...
[!] Unable to import module ssl: No module named 'humanize'
[!] Unable to find a module named ssl

Listing the tools module with wapiti --list-modules, there is no ssl module listed but its being loaded by default with the default scan.

**Comment by bretfourbe** [comment]
Hi @zero13ro, if you need to launch ssl module, you have to install these dependencies (`pip install .[ssl]`) : `humanize` and `sslyze`.
You can specify which modules you need using `-m sql,xss,csp` for instance.
