### ISSUE TITLE
Mettre à jour la version du package cryptography

### ISSUE THREAD

**Issue by fwininger** [wapiti-scanner/wapiti#509]
Le package actuellement dans le piplock est vulnérable. Mettre à jour !

**Comment by bretfourbe** [comment]
Knwon issue : https://github.com/wapiti-scanner/wapiti/security/dependabot/10
We can't fix it at the moment since the latest installable `cryptography` module version is `38.0.4` and fixed version `41.0.4`.

**Comment by bretfourbe** [comment]
It seems it is due to `mitmproxy` version which is fixed, latest version allows the use of the latest `cryptography` version
