### ISSUE TITLE
wapiti crashes when -x is used

### ISSUE THREAD

**Issue by albertcuy** [wapiti-scanner/wapiti#549]
Good Day,

So i've been testing wapiti 3.0.4 on Kali 2023.4 against a server running dvwa. i made a script that generates the cookie, which is immediately fed into the wapiti scan:

wapiti-getcookie -u http://test-server/login.php -c /home/user01/cookie.json  -A Firefox
wapiti -a admin%password -u http://test-server  -x http://test-server/logout.php -c /home/user01/cookie.json

i am immediately met with the following error below.  Seems like the parser doesn't like the URL i'm passing with -x.

####################################################################################################
     __      __               .__  __  .__________
    /  \    /  \_____  ______ |__|/  |_|__\_____  \
    \   \/\/   /\__  \ \____ \|  \   __\  | _(__  <
     \        /  / __ \|  |_> >  ||  | |  |/       \
      \__/\  /  (____  /   __/|__||__| |__/______  /
           \/        \/|__|                      \/
Wapiti-3.0.4 (wapiti.sourceforge.io)
Traceback (most recent call last):
  File "/usr/bin/wapiti", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.0.4', 'console_scripts', 'wapiti')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 1206, in wapiti_main
    wap.browse()
  File "/usr/lib/python3/dist-packages/wapitiCore/main/wapiti.py", line 328, in browse
    for resource in explorer.explore(self._start_urls, self._excluded_urls):
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 659, in explore
    regexes.append(wildcard_translate(excluded_url))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wapitiCore/net/crawler.py", line 95, in wildcard_translate
    return re.compile(res + r'\Z(?ms)')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/__init__.py", line 294, in _compile
    p = _compiler.compile(pattern, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_compiler.py", line 743, in compile
    p = _parser.parse(p, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 982, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 457, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/re/_parser.py", line 843, in _parse
    raise source.error('global flags not at the start '
re.error: global flags not at the start of the expression at position 34

####################################################################################################

i went into this rabbit hole as wapiti seems to be missing a lot of vulnerabilities. i've read some posts suggesting that 
i exclude logout.php so as not the invalidate the generated cookie.

 i've already set security to low on config-inc.php.

Any comments/suggestions? tia

**Comment by bretfourbe** [comment]
Hii @albertcuy, 
Indeed thank you for noticing the issue on Kali, but Wapiti 3.0.4 is an old version. Can you try using the github version (see here https://github.com/wapiti-scanner/wapiti/blob/master/INSTALL.md#installing-wapiti-from-the-git-repository) ?

Also regarding your command line : 
> wapiti -a admin%password -u http://test-server -x http://test-server/logout.php -c /home/user01/cookie.json

I think you don't need to specify credentials again since cookies should be valid, so just use the following : 
`wapiti -u http://test-server -x http://test-server/logout.php -c /home/user01/cookie.json`
