### ISSUE TITLE
Add an option --wapp-dir to load wapp data

### ISSUE THREAD

**Issue by Qwarctick** [wapiti-scanner/wapiti#561]
There is an option `--wapp-url` that take the URL of a github repo to update wapp data. The option expects an url that leads to the raw data. Wapiti then completes this url to obtain the files. So if you use https://raw.githubusercontent.com/wapiti-scanner/wappalyzer/main as input, wapiti will download the file https://raw.githubusercontent.com/wapiti-scanner/wappalyzer/main/src/groups.json.

 This works well on github because to get the raw files, all you have to do is change the root of the url. (github.com -> raw.githubusercontent.com).

But it doesn't work with gitea, where you have to add the raw parameter at the end of the url, or on private repositories, where you sometimes have to add the parameter at the end of the URL (in addition to adding the tokens).

I suggest adding a `--wap-dir` option that leads to a folder containing the tree structure required for the files.

**Comment by Slokilla** [comment]
Fixed in https://github.com/wapiti-scanner/wapiti/pull/568
