### ISSUE TITLE
Endpoints Documentation

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#59]
Hello,

I'm trying to implement my own endpoints for xxe and ssrf attacks but I noticed there is no documentation for those.

It took my some times to figure it out and I think it could be nice to have informations like : 

- The list of urls (get_ssrf/ssrf/xoxo/xxe/dtd)
- What they do
- what they need
- wht they return

**Comment by devl00p** [comment]
I added a markdown file in doc/ for the xxe module. You can already give a look and see if you find it understandable enough.

https://github.com/wapiti-scanner/wapiti/commit/dd7b752323550b218ab1c4db946b32bc0bb64c89?short_path=7e9bcf9#diff-7e9bcf91255d6f9ff0753e794f13f16b8983799abc02ded6c87040d735a86b35

**Comment by jinxka** [comment]
Yes it's understandable and it gives the needed information

**Comment by devl00p** [comment]
More information on endpoints added, not XXE specific : https://github.com/wapiti-scanner/wapiti/blob/f9e27c173b244a203e9c9c040b1b3785420dc50e/doc/endpoints.md
