### ISSUE TITLE
is wapiti can only use for get or  post(x-www-form-urlencoded) request?

### ISSUE THREAD

**Issue by weiyaojun1992** [wapiti-scanner/wapiti#599]
I'm a QA, now I plan to use wapiti3 for my project， but when I debug and test wapiti3 I find it can only  be useful for get or   post（Content-Type=application/x-www-form-urlencoded）,and is wapiti can only use for coding by php program? I use wapiti -u  http://domain ,there is on www.domain.com request record on my proxy，scan nothing

**Comment by bretfourbe** [comment]
Hi @weiyaojun1992, 
You can use it for JSON body, but you will need to provide a swagger file of the API (using `--swagger`) or to use the headless mode (`--headless`).
