### ISSUE TITLE
Endpoints params

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#60]
Hello,

While working on endpoints I noticed that some params changed there name often for no reason.

For example, *session_id* is called *session_id*, *random_id* or just *id*, sometimes in the same file. If it's the session_id it should always be called *session_id* no matter where. Same issue with *path_id*

**Comment by devl00p** [comment]
Indeed we should name it `session_id` everywhere. For the second one `request_id` may be more explicit.
