### ISSUE TITLE
Error in launch wapiti (Windows 10)

### ISSUE THREAD

**Issue by TannicArcher** [wapiti-scanner/wapiti#613]
OS Windows 10
C:\Users\TannicArcher\wapiti\bin>python wapiti --update
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\TannicArcher\AppData\Roaming\Python\Python312\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'

 ██╗    ██╗ █████╗ ██████╗ ██╗████████╗██╗██████╗
 ██║    ██║██╔══██╗██╔══██╗██║╚══██╔══╝██║╚════██╗
 ██║ █╗ ██║███████║██████╔╝██║   ██║   ██║ █████╔╝
 ██║███╗██║██╔══██║██╔═══╝ ██║   ██║   ██║ ╚═══██╗
 ╚███╔███╔╝██║  ██║██║     ██║   ██║   ██║██████╔╝
  ╚══╝╚══╝ ╚═╝  ╚═╝╚═╝     ╚═╝   ╚═╝   ╚═╝╚═════╝
Wapiti 3.2.0 (wapiti-scanner.github.io)
[*] Updating modules
Updating module wapp
Downloading CVE data for angularjs
Downloading CVE data for apache
Downloading CVE data for drupal
Downloading CVE data for jetty
Downloading CVE data for joomla
Downloading CVE data for jquery
Downloading CVE data for nextjs
Downloading CVE data for nginx
Downloading CVE data for nodejs
Downloading CVE data for openssl
Downloading CVE data for php
Downloading CVE data for prestashop
Downloading CVE data for spip
Downloading CVE data for tomcat
Downloading CVE data for underscorejs
Downloading CVE data for wordpress
Update done.
Error: None is not a valid domain name
Updating module htp
Update done.
Updating module nikto
Update done.

**Comment by devl00p** [comment]
The error is tied to the `mitmproxy` dependency of Wapiti.

`mitmproxy` relies on `passlib` which itself relies on `bcrypt`.

You can read more about the issue here: https://github.com/kernelci/kernelci-api/issues/520

We are currently using mitmproxy 10.2.3. You can try to upgrade mitmproxy to the latest version (10.4.2)

Note that Wapiti on Windows is not officially supported, we recommend to use WSL (Windows Subsystem Linux)

Even if you manage to fix that `bcrypt` issue there may be other issues related to the `cryptography` depencency on Windows.

**Comment by TannicArcher** [comment]
> The error is tied to the `mitmproxy` dependency of Wapiti.
> 
> `mitmproxy` relies on `passlib` which itself relies on `bcrypt`.
> 
> You can read more about the issue here: [kernelci/kernelci-api#520](https://github.com/kernelci/kernelci-api/issues/520)
> 
> We are currently using mitmproxy 10.2.3. You can try to upgrade mitmproxy to the latest version (10.4.2) and maybe it will upgrade dependencies in chain.
> 
> Note that Wapiti on Windows is not officially supported, we recommend to use WSL (Windows Subsystem Linux)
> 
> Even if you manage to fix that `bcrypt` issue there may be other issues related to the `cryptography` depencency on Windows.

Thanks for answer
