### ISSUE TITLE
Remove "yield" from attack modules

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#73]
The `yield` of either the original request to attack or the exception that occured during the attack was implemented some times ago for several reasons:

- ctrl+c feature allowing to pause a module and resume it on a request granularity
- capture exceptions to count the number of network exceptions and generate a crash report for more serious exceptions
- having some way to see the progress and later implement a progress bar (tqdm)
- keep the modules logic independant enough

Unfortunately it is very clumsy and hard to deal with it correctly. It is also an obstacle to everybody that would want to write a new module.

So let's remove that `yield` atrocity.

In order to keep the ctrl+c feature with catch of exceptions we have to deal with the attack of each resource separately.

The idea is to change the `attack` method on `attack.Attack` to accept a `Request` parameter.

Tasks:

- Need to be very cautious with regressions (existing tests will help but all modules should be tested manually also).
- Some modules may use local vars to keep some kind of state, they then should be moved to class/instance attributes.
- Some modules directly filtered resources based on some constraints defined in the module code. As we have to move that logic (constraints may be based or previously mentionned state vars) we can take advantage of a new method (`must_attack`) to see if a request is discarded by the module. We may want to use that information later.
- Some modules don't care about resources passed as arguments and just attack the root URL (buster, csp, nikto, etc). They should only be triggered on that root URL though. It will also allow to improve later the `domain` scope for those modules.
- Check twice how network exceptions are dealt with... maybe the new `attack` function should return something (0: succes, more: number of missed requests?)

**Comment by devl00p** [comment]
Work In Progress

**Comment by bretfourbe** [comment]
Hi @devl00p, i think this issue can be closed now :)
