### ISSUE TITLE
Remove Base64 encoding from xxe_dtd

### ISSUE THREAD

**Issue by jinxka** [wapiti-scanner/wapiti#81]
Hello,

Currently, the xxe module only works on php websites because the dtd requires it to run `php://filter/read=convert.base64-encode/resource=` which encode the data so that the url won't break on special caracters.

We just need to test if the website is vulnerable to xxe attacks so I was wondering if we could change the files extracted to something like `file:///proc/version` or `file:///etc/lsb-release` which never contains any special charater, this will render the encoding useless.

Then, we could remove the php method, allowing the xxe_module to work on all websites.

What are your thoughts on this?

**Comment by jinxka** [comment]
For Windows `file:///c:/windows/win.ini` could probably do the trick.

**Comment by devl00p** [comment]
I remember seing issues when files contained a new line character: it generated an invalid URL and the endpoint wasn't contacted.

Of course if depends on the implementation but we should at least make sure current tests will work without encoding. 
Unfortunately finding a Linux system file without new line may be hard (`/proc/version` has a traling new line for example).

/proc/self/cmdline may be a good candidate though

Pentesterlab also have a VM that can be used for testing https://pentesterlab.com/exercises/play_xxe/course

**Comment by devl00p** [comment]
✅ New versions of the scripts put on wapiti3.ovh
