### ISSUE TITLE
HTTP request and cURL command hidden on html report

### ISSUE THREAD

**Issue by Hyatche** [wapiti-scanner/wapiti#86]
Hello, when i export the report on html format the http request and cURL command are hidden. 
They are written in the source code but are part of the is-hidden class, which is not displayed (css code display: none!important;). But when I click on HTTP Request on the tab http request stay hidden and description stay display. 
So when I read the html report I can't see http request or cURL command if I doesn't remove manualy display: none!important of class .is-hidden.

**Comment by devl00p** [comment]
Hello,

How did you install wapiti ? Did you used  `pip install` or did you use a package from a Linux distribution or another method ?

Regards

**Comment by Hyatche** [comment]
I used the version 3.0.4 on parrot distribtution. I have also teast with the last commit (85973a9335fa9bc2066f70563d10dab36533d034) and the issue as same.

**Comment by bretfourbe** [comment]
Hi @Hyatche,
Could you provide us the command you used for your test please ?
Thnaks in advance.

**Comment by Hyatche** [comment]
Hello, the command is : 
`wapiti -u URL -m sql,wapp,nikto,xss -f html -o output`.
For information I have test the html file on different browser like brave, firefox, chrome but the issue as same.

**Comment by bretfourbe** [comment]
Ok, and could you tell me for what kind of vulnerabilities it happened please ? Like SQL injections, Cross Site Scripting, etc. ?
@Hyatche

**Comment by Hyatche** [comment]
@bretfourbe It's happend for every vulnerabilities.

**Comment by bretfourbe** [comment]
@Hyatche Can you check that /js/kube.min.js is in your output directory ?
The only way i reproduced this behavior was when removing this file from the output directory.

**Comment by Hyatche** [comment]
@bretfourbe I didn't have js directory, or js file, on the output directory.

**Comment by Hyatche** [comment]
Ok I check it for some reason i didn't have js directory on my wapitiCore/report_template.

**Comment by bretfourbe** [comment]
Ok, when generating the html report it is supposed to copy the js file from wapitiCore/report_template into output directory, that is why it was missing.
Is it good for you now @Hyatche ?

**Comment by bretfourbe** [comment]
@devl00p do you think /js/kube.min.js is missing in the wapiti 3.0.4 version ?

**Comment by Hyatche** [comment]
Yep @bretfourbe I add it and now it's good, thank you for your help !

**Comment by babu-dot** [comment]
Hate to drag this up again, but I'm in the same boat as Hyatche. I created the js directory (which was missing like Hyatche's was) in wapitiCore/report_template and copying the kube.min.js file into it. With it all there, I still have the same problem with HTTP and curl being hidden in the report. Maybe I'm missing the part that tells it to go look there somehow?
