### ISSUE TITLE
Reading Urls from file

### ISSUE THREAD

**Issue by Yvtq8K3n** [wapiti-scanner/wapiti#87]
I have been trying to read a list of URLs from a given txt file as described on the man page: https://wapiti.sourceforge.io/wapiti.1.html

`
-s, --start URL
You can also give it a filename and Wapiti will read URLs from the given file (must be UTF-8 encoded), one URL per line.`

Is there any example I could use? Im currently trying like this:
wapiti -u http://test.pt --start /home/user/UrlList.txt --store-session /home/user/DB

**Comment by bretfourbe** [comment]
Hi @Yvtq8K3n, 
What do you need to know exactly ?
Using `wapiti -u http://test.pt --start /home/user/UrlList.txt --store-session /home/user/DB`, wapiti should start by crawling the specified URLs in your file UrlList.txt.

**Comment by Yvtq8K3n** [comment]
It seems I had an old version of wapiti. Reinstalling the latest version solved the problem.
