### ISSUE TITLE
Does it support the output result in Chinese?

### ISSUE THREAD

**Issue by xx132917** [wapiti-scanner/wapiti#91]
Does it support the output result in Chinese?

**Comment by bretfourbe** [comment]
Hi @xx132917,
Wapiti uses the system locale to select the output language.
I think there is a chinese file for translations here https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/language_sources/zh.po but several translations are missing.
Here is the english version : https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/language_sources/en.po.
If you can help on that, feel free to complete the chinese version :)

**Comment by devl00p** [comment]
@xx132917 Wapiti is registered on Transifex so if you want you can suggest chinese translations using this website, it makes the task less painfull than just editing text files :)

https://www.transifex.com/none-538/wapiti/

**Comment by devl00p** [comment]
Closing the issue, the response is Yes wapiti supports the chinese output (ZH) but the translation is currently incomplete
