### ISSUE TITLE
Sometimes test_resume_crawling fails, only on github actions

### ISSUE THREAD

**Issue by bretfourbe** [wapiti-scanner/wapiti#96]
Hi,
Sometimes test_resume_crawling (in test_crawl.py) fails, but only on github actions. I can't reproduce on my side...
![image](https://user-images.githubusercontent.com/27951656/112718142-5472bc00-8ef1-11eb-90ec-e81f89a05ff8.png)
@devl00p if you have any clue ?

**Comment by devl00p** [comment]
Only possible reason seems that the order of links extracted from a webpage is not guaranteed, I changed the test so it check if it page 9 or 11
